### ISSUE TITLE
move CSS to a new file 

### ISSUE THREAD

**Issue by tandavas** [santiparpa/thailandcovid19#2]
Move CSS to a separate file https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_is_structured

https://github.com/santiparpa/thailandcovid19/blob/eeb2d76173ad951a59cc0ca3c99adab9a40bff8b/index.html#L152

**Comment by santiparpa** [comment]
Complete!

**Comment by tandavas** [comment]
👍
